bilibop-rules: in pvfilter.sh and physical_volumes_filter, add support for 'global_filter': - Modify _pvfilter_init_lvm_configfile() and _pvfilter_init_device_filters() - Add --noglobal option to be able to set 'filter' when 'global_filter'   is enabled.

diff --git a/usr/share/bilibop/physical_volumes_filter b/usr/share/bilibop/physical_volumes_filter
--- a/usr/share/bilibop/physical_volumes_filter
+++ b/usr/share/bilibop/physical_volumes_filter
@@ -9,8 +9,8 @@ set -e
 
 PATH="/sbin:/bin:/usr/bin"
 PROG="${0##*/}"
-SOPTS="a:bDd:f:ghilor:sux:"
-LOPTS="accept:,blank,default,delimiter:,exclude:,file:,global,help,init,list-pv,overwrite,reject:,show,udev"
+SOPTS="a:bDd:f:ghilnor:sux:"
+LOPTS="accept:,blank,default,delimiter:,exclude:,file:,global,help,init,list-pv,noglobal,overwrite,reject:,show,udev"
 
 # Check if 'lvm' is installed; if not, exit unconditionally.
 have_lvm="1"
@@ -40,6 +40,7 @@ udev="false"        # --udev
 accept_all="false"  # --accept all
 filter="false"      # --accept, --reject, --exclude
 global="false"      # --global
+noglobal="false"    # --noglobal
 B="|"; E="${B}"     # --delimiter
 
 exit_code=""        # for -o with unwritable file
@@ -71,10 +72,10 @@ See also lvm.conf(5) for some details.
 Usage:
   ${PROG} [--file FILE]
   ${PROG} --help
-  ${PROG} --init [--file FILE] [--global]
+  ${PROG} --init [--file FILE] [--global|--noglobal]
   ${PROG} --default [--show] [--file FILE]
   ${PROG} --list-pv [--show] [--udev]
-  ${PROG} [--blank] [--file FILE] [--global] [--overwrite] [--show] [--udev] [--delimiter ?] [--accept ARG] [--reject ARG] [--exclude ARG]
+  ${PROG} [--blank] [--file FILE] [--noglobal] [--overwrite] [--show] [--udev] [--delimiter ?] [--accept ARG] [--reject ARG] [--exclude ARG]
 
 Options:
   -a ARG, --accept=ARG
@@ -113,18 +114,25 @@ Options:
         not supported (i.e. lvm2 < 2.02.98), this option is silently
         ignored. Note that this variable is not set by default.
         If 'global_filter' is supported and if it is set (even with an
-        empty array), then --global is implicit.
+        empty array), then --global is implicit. See also --noglobal.
 
   -h, --help
         Print this message on stdout and exit.
 
   -i, --init
-        Initialize lvm.conf if one of the file, the 'devices' section
-        or the 'filter' or 'obtain_device_list_from_udev' variables
-        are missing. Filter is then set to its default value.
+        Initialize lvm.conf if one of the file itself, its 'devices'
+        section, or the 'filter' or 'obtain_device_list_from_udev'
+        variables are missing. Filter is then set to its default value
+        (i.e. [ "a|.*|" ] for 'filter', [ ] for 'global_filter').
 
   -l, --list-pv
         List block devices with LVM2_member fstype and exit.
+
+  -n, --noglobal
+        Do not modify 'global_filter', even if it is already set. This
+        overrides the implicit behaviour of the --global option, and
+        forces the command to be applied to the 'filter' variable. See
+        also --global.
 
   -o, --overwrite
         Overwrite the configuration file (lvm.conf).
@@ -175,6 +183,12 @@ while true; do
 			;;
 		-g|--global)
 			global="true"
+			noglobal="false"
+			shift
+			;;
+		-n|--noglobal)
+			noglobal="true"
+			global="false"
 			shift
 			;;
 		-f|--file)
@@ -242,11 +256,18 @@ done
 # Options will be parsed again:
 eval set -- "${ARGS}"
 
-# Fix the behaviour of the --global option:
+# Fix the behaviour of the --global/--noglobal options: if 'global_filter' is
+# supported and is set, the command will be applied to it, unless --noglobal
+# is invoked; if 'global_filter' is supported but not set, the command will
+# be applied to 'filter', unless --global is invoked (with --init); and if
+# 'global_filter' is not supported, --global/--noglobal are silently ignored.
 if _pvfilter_has_global; then
-	grep -qs '^\s*global_filter\s*=\s*\[.*\]' ${LVM_CONF} &&
-	global="true"
+	global_filter_is_supported="true"
+	if grep -qs '^\s*global_filter\s*=\s*\[.*\]' ${LVM_CONF}; then
+		[ "${noglobal}" = "true" ] || global="true"
+	fi
 else
+	global_filter_is_supported="false"
 	global="false"
 fi
 # ===========================================================================}}}
@@ -266,8 +287,15 @@ if [ "${1}" = "--" ] ||
 		0)
 			grep '^\s*obtain_device_list_from_udev\s*=' ${LVM_CONF} ||
 			not_found=$((not_found+$?))
-			grep '^\s*filter\s*=' ${LVM_CONF} ||
-			not_found=$((not_found+$?))
+
+			if [ "${global_filter_is_supported}" = "true" ]; then
+				grep '^\s*\(global_\)\?filter\s*=' ${LVM_CONF} ||
+				not_found=$((not_found+$?))
+			else
+				grep '^\s*filter\s*=' ${LVM_CONF} ||
+				not_found=$((not_found+$?))
+			fi
+
 			[ "${not_found}" != "0" ] &&
 				echo "${PROG}: a needed variable is not defined in ${LVM_CONF}" >&2 &&
 				echo "Use '--init' option to create it." >&2
@@ -462,7 +490,11 @@ trap "rm -f ${LVM_TEMP}" 0 2 3 6 9 15
 [ "${udev}" = "true" ] && u=1 || u=0
 sed "s,^\(\s*obtain_device_list_from_udev\s*=\s*\).*,\1${u}," ${LVM_CONF} >${LVM_TEMP}
 
-if [ "${blank}" = "true" ]; then
+if [ "${global}" = "true" -a "${blank}" = "true" ]; then
+	sed -i "s?^\(\s*global_filter\s*=\s*\[\).*]?\1${FILTER_STRING:+ ${FILTER_STRING}} ]?" ${LVM_TEMP}
+elif [ "${global}" = "true" ]; then
+	sed -i "s?^\(\s*global_filter\s*=\s*\[\)?\1${FILTER_STRING:+ ${FILTER_STRING}, }?" ${LVM_TEMP}
+elif [ "${blank}" = "true" ]; then
 	sed -i "s?^\(\s*filter\s*=\s*\[\).*]?\1${FILTER_STRING:+ ${FILTER_STRING}} ]?" ${LVM_TEMP}
 else
 	sed -i "s?^\(\s*filter\s*=\s*\[\)?\1${FILTER_STRING:+ ${FILTER_STRING}, }?" ${LVM_TEMP}
@@ -476,10 +508,17 @@ if [ "${overwrite}" = "true" ]; then
 	fi
 
 	if [ "${show}" = "true" ]; then
-		grep '^\s*\(filter\|obtain_device_list_from_udev\)\s*=' ${LVM_CONF}
+		if [ "${global_filter_is_supported}" = "true" ]; then
+			grep '^\s*\(\(global_\)\?filter\|obtain_device_list_from_udev\)\s*=' ${LVM_CONF}
+		else
+			grep '^\s*\(filter\|obtain_device_list_from_udev\)\s*=' ${LVM_CONF}
+		fi
 	fi
+
+# Show only (--show is implicit when --overwrite is not invoked):
+elif [ "${global_filter_is_supported}" = "true" ]; then
+	grep '^\s*\(\(global_\)\?filter\|obtain_device_list_from_udev\)\s*=' ${LVM_TEMP}
 else
-	# Show only (--show is implicit when --overwrite is not invoked):
 	grep '^\s*\(filter\|obtain_device_list_from_udev\)\s*=' ${LVM_TEMP}
 fi
 
